pull docker image from jfrog and test

diff --git a/.github/workflows/arctiq-mission.yml b/.github/workflows/arctiq-mission.yml
--- a/.github/workflows/arctiq-mission.yml
+++ b/.github/workflows/arctiq-mission.yml
@@ -235,17 +235,18 @@ jobs:
          sleep 10
 
        # Test if the app is responding
-         RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
-         echo "HTTP response code: $RESPONSE"
+     - name: Test if the app is responding
+       run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+        echo "HTTP response code: $RESPONSE"
 
-         if [ "$RESPONSE" -eq 200 ]; then
-           echo "Tetris game is running successfully!"
-         else
-           echo "Failed to reach Tetris game. Response code: $RESPONSE"
-           docker logs game
-           exit 1
-         fi
-
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "Tetris game is running successfully!"
+        else
+          echo "Failed to reach Tetris game. Response code: $RESPONSE"
+          docker logs game
+          exit 1
+       fi
 
       # - name: Update kubeconfig
       #   run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD
